main:
    data: 'sqlite:///data/data.db'

logging:
    version: 1
    formatters:
        simple:
            format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    handlers:
        console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    loggers:
        simple:
            level: DEBUG
    root:
        level: DEBUG
        handlers: [console]

# vim: set ft=yaml:
